### ISSUE TITLE
Roll on program start

### ISSUE THREAD

**Issue by smint80** [adams85/filelogger#10]
I would like to be able to enable a setting for always creating next file on program start nomatter how big the file last used is.

**Comment by deanwiles** [comment]
To get a unique filename on program start, you can leverage the [CustomBehavior](https://github.com/adams85/filelogger/tree/master/samples/CustomBehavior) sample that @adams85 provided. I added a <startdate> template placeholder to the file path, so that the filename contains the start date & time (e.g. "Path": "&lt;appname&gt;-&lt;startdate:yyyyMMdd-HHmmss&gt;-&lt;counter:000&gt;.log"). 
See my CustomFileLoggerProcessor.cs in [WFAppLogger](https://github.com/deanwiles/WFAppLogger) for an example of how to implement this.

**Comment by adams85** [comment]
I doubt that this requirement is too common, so I don't think it's worth introducing a new setting.

However, it's achievable pretty easy by customization of the logger processor. So @deanwiles pointed you in the right direction. I can only add to his comment that you don't need to include the datetime in the file name to get this behavior.

I'd rather do something like this:
```csharp
public class CustomFileLoggerProcessor : FileLoggerProcessor
{
    public CustomFileLoggerProcessor(FileLoggerContext context) : base(context) { }

    protected override LogFileInfo CreateLogFile(ILogFileSettings fileSettings, IFileLoggerSettings settings)
    {
        LogFileInfo logFile = base.CreateLogFile(fileSettings, settings);

        var dummyEntry = new FileLogEntry
        {
            Text = string.Empty,
            Timestamp = Context.GetTimestamp()
        };

        while (logFile.FileAppender.FileProvider.GetFileInfo(Path.Combine(logFile.BasePath, FormatFilePath(logFile, dummyEntry))).Exists)
            logFile.Counter++;

        return logFile;
    }
}
```

This way the counter will be set to the first unused number when the log file gets created and you only need to include a counter in your log file name templates (e.g. myapp-<counter:000>.log). Just check out the CustomBehavior sample for how to wire up the customization.

**Comment by deanwiles** [comment]
Hi @adams85. Thanks for the feedback. Using the Context's timestamp will change over time or over dates, which may be desirable for a continually-running service like a website. However if my case (and possibly @smint80's), my app is a WinForm client exe and I want to get the logs associated with a particular user's run of the app, so app start date/time is preferable to Context timestamp. Hope that makes sense. Or am I missing something?

**Comment by adams85** [comment]
@deanwiles No, you aren't. I see where you are getting at.

In that case this should work for you:

```csharp
public class CustomFileLoggerProcessor : FileLoggerProcessor
{
    private readonly DateTimeOffset _startupTimestamp;

    public CustomFileLoggerProcessor(FileLoggerContext context) : base(context) 
    {
        _startupTimestamp = DateTimeOffset.UtcNow;
    }

    protected override LogFileInfo CreateLogFile(ILogFileSettings fileSettings, IFileLoggerSettings settings)
    {
        LogFileInfo logFile = base.CreateLogFile(fileSettings, settings);

        while (logFile.FileAppender.FileProvider.GetFileInfo(Path.Combine(logFile.BasePath, FormatFilePath(logFile, null))).Exists)
            logFile.Counter++;

        return logFile;
    }

    protected override string GetDate(string inlineFormat, LogFileInfo logFile, FileLogEntry entry)
    {
        return _startupTimestamp.ToLocalTime().ToString(inlineFormat ?? logFile.DateFormat, CultureInfo.InvariantCulture);
    }
}
```

**Comment by guidomocha** [comment]
see my gist for easy and clean workaround
https://gist.github.com/guidomocha/1ac375e9fe215c6f7f2649b4007ea9fa
