### ISSUE TITLE
Change of month while logging to file does not reset counter

### ISSUE THREAD

**Issue by Surdna** [adams85/filelogger#21]
Hello,
While using logger I saw that in case of month change, counter do not reset in new path. 
In config I've set path to:
"Files": [ { "Path": "Logs/<date:yyyy>/<date:MM>/<counter>.log" } ]
and it works great for most of the time but while advancing to next month I get more or less:

>     Logs/2022/02/000.log
>     ...
>     Logs/2022/02/005.log
>     (after date change)
>     Logs/2022/03/005.log

I'm not sure if it's expected behaviour and I guess I can change it for myself in FileLoggerProcessor.cs->UpdateFilePath but it would be great to confirm that with creators.

Thanks,
Surdna

**Comment by adams85** [comment]
Hi!

Thanks for the report. This behavior was not by design.

v3.3.0 fixes it.
