### ISSUE TITLE
JSON Format differences to JsonConsoleLogger

### ISSUE THREAD

**Issue by markusschaber** [adams85/filelogger#26]
Hi,
I'm evaluating Karambolo.Extensions.Logging.File.Json and the README states: 

> The code is based on [ConsoleLogger](https://github.com/dotnet/runtime/tree/master/src/libraries/Microsoft.Extensions.Logging.Console) whose full feature set is implemented

But while experimenting, I found some small differences to `AddJsonConsole()`.

First, it looks like Karambolo separates entries with a ',', while the console logger only uses line break.

Second, the `JsonConsoleFormatterOptions` [accept](https://learn.microsoft.com/en-us/dotnet/core/extensions/console-log-formatter#json) `JsonWriterOptions`, where we can set '`Indented = false`'.

This combination allows us to write the [JSON lines](https://jsonlines.org/) (aka [NDJSON](https://github.com/ndjson/ndjson-spec)) format, each log entry on a single line, with the console logger.

Would you implement the changes, or accept patches, to enable JSON lines support?

**Comment by adams85** [comment]
Hi @markusschaber,

You can pass `JsonWriterOptions` to the logger using [this configuration overload](https://github.com/adams85/filelogger/blob/3.4.0/source/FileLogger.Json/JsonFileLoggerExtensions.cs#L31) as follows:

```csharp
builder.Logging.AddJsonFile(textBuilder: new JsonFileLogEntryTextBuilder(jsonWriterOptions), configure: o => { /* ... */ });
```

For further customization, you can subclass [`JsonFileLogEntryTextBuilder`](https://github.com/adams85/filelogger/blob/3.4.0/source/FileLogger.Json/JsonFileLogEntryTextBuilder.cs) and pass an instance of that to the method above. For example, to remove the trailing comma, you'll need to override the `BuildEntryText` method.

 > Would you implement the changes, or accept patches, to enable JSON lines support?

Improvements are welcome!

**Comment by adams85** [comment]
FYI: in the latest version, I added some convenience methods along with an option class so you don't need to subclass `JsonFileLogEntryTextBuilder` any more if you just want to change the separator between entries:
```csharp
builder.Logging.AddJsonFile(new JsonFileLogFormatOptions { JsonWriterOptions = new JsonWriterOptions { Indented = false }, EntrySeparator = "" }
```
