### ISSUE TITLE
Is it possible to implement a log rotate, log.N.txt renames to log.N+1.txt

### ISSUE THREAD

**Issue by rheatley-pervasid** [adams85/filelogger#27]
I see issue #2 was closed with, do it externally, but I really need some feature of this library to have
- the latest file is always log.0.txt, the next oldest is log.1.txt, etc.
- fixed number of log files, e.g. 5
- rotate on max file size
- when rotate happens, log.0.txt is renamed to log.1.txt
- log.4.txt is deleted before the rename

I can almost write this
```
protected override bool UpdateFilePath(LogFileInfo logFile, FileLogEntry entry, CancellationToken cancellationToken)
{
    var res = base.UpdateFilePath(logFile, entry, cancellationToken);
    if (logFile.Counter == 0)
    {
        return res;
    }

    const int maxFiles = 5;
    logFile.Counter = maxFiles - 1;
    var p = Path.Combine(logFile.BasePath, this.FormatFilePath(logFile, entry));
    File.Delete(p);

    for (int i = maxFiles; i > 1; i--)
    {
        logFile.Counter = i - 1;
        var p1 = Path.Combine(logFile.BasePath, this.FormatFilePath(logFile, entry));

        logFile.Counter = i - 2;
        var p2 = Path.Combine(logFile.BasePath, this.FormatFilePath(logFile, entry));

        try
        {
            File.Move(p2, p1);
        }
        catch (FileNotFoundException)
        {
        }
    }

    logFile.Counter = 0;
    return base.UpdateFilePath(logFile, entry, cancellationToken);
}
``` 

**But** I cannot actually use this with `LogFileAccessMode.KeepOpen` as the file is in use.
logFile.Close() is internal...

Assuming I haven't missed something, is it possible to request something like
- change accessibility of logFile.Close()
- or, a logFile close callback? then I could implement the rename in that, and reset counter back to 0

**Comment by adams85** [comment]
Sure, I'll take a look soon which option is better to enable your use case. Until then, you may use reflection to call the internal method.

**Comment by adams85** [comment]
I introduced a [new extension point](https://github.com/adams85/filelogger/blob/3.5.0/source/FileLogger/FileLoggerProcessor.cs#L423), which makes possible what you want to achieve. I even added a [sample app](https://github.com/adams85/filelogger/tree/master/samples/LogRotation) to show the full solution. (If you're ok with hardcoding the file number limit, you may get rid of the extension of options.)

**Comment by rheatley-pervasid** [comment]
@adams85 that's great. Thank you for a speedy fix :)
