### ISSUE TITLE
Replace System.Threading.Task.Dataflow with System.Threading.Channels

### ISSUE THREAD

**Issue by TechInterMezzo** [adams85/filelogger#5]
This is more lika a suggestion.
Maybe this library could benefit from channels.

Here is a blog post I find quite easy to understand: https://ndportmann.com/system-threading-channels/

Channels seem to be a more recent development than the dataflow library. They have a clean API and seem to focus on solving the problem of fast and thread safe queues.

**Comment by adams85** [comment]
Thanks for the tip! Dataflow may be a bit heavy-weight for the use case of this lib indeed. Furthermore, chances are that overall performance would benefit from Channels as well. It's definitely worth giving it a go.
