### ISSUE TITLE
Counter Start value setting

### ISSUE THREAD

**Issue by GGY-CM** [adams85/filelogger#6]
Hi,

Can you add a setting to allow set the start value of the counter? or set its start value to 1 instead of 0?

Thanks,

**Comment by adams85** [comment]
You can achieve this pretty easy by subclassing FileLoggerProcessor and overriding the [GetCounter virtual method](https://github.com/adams85/filelogger/blob/3.0.0/source/FileLogger/FileLoggerProcessor.cs#L239).

I put together a [sample console app](https://github.com/adams85/filelogger/tree/3.0/samples/CustomBehavior) for you to demonstrate how to do this.

However, I'll consider introducing some hook to control this from the settings. A CounterFormatter callback or something.

**Comment by GGY-CM** [comment]
Thank you very much.

**Comment by adams85** [comment]
Version 3.2.0 introduces the previously mentioned hook mechanism. Now this is possible through configuration, without subclassing anything:

```csharp
builder.AddFile(o =>
{
    o.RootPath = AppContext.BaseDirectory;

    o.PathPlaceholderResolver =  (placeholderName, inlineFormat, context) =>
        placeholderName == "counter" ? 
        (context.Counter + 1).ToString(inlineFormat ?? context.CounterFormat, CultureInfo.InvariantCulture) :
        null;
});
```
