### ISSUE TITLE
Path variable <appname>

### ISSUE THREAD

**Issue by GGY-CM** [adams85/filelogger#7]
Maybe add a new variable <appname> like <counter> in the Path, and replace it to current application name in code?

Thanks,

**Comment by adams85** [comment]
[The sample](https://github.com/adams85/filelogger/tree/3.0/samples/CustomBehavior) mentioned in your other issue shows a possible solution to this.

However, application name is static (I mean it don't change during a single run), so you can get along even without subclassing:

    builder.AddFile(o =>
    {
        o.RootPath = AppContext.BaseDirectory;
        var appName = Assembly.GetEntryAssembly().GetName().Name;
        foreach (var file in o.Files)
            file.Path = file.Path.Replace("<appname>", appName);
    });

There are already at least two easy ways to achieve this behavior, therefore I don't think it's worth supporting this by default.

**Comment by adams85** [comment]
Version 3.2.0 introduces a setting which properly handles this without the need of subclassing:

```csharp
builder.AddFile(o =>
{
    o.RootPath = AppContext.BaseDirectory;

    var appName = Assembly.GetEntryAssembly().GetName().Name;
    o.PathPlaceholderResolver = (placeholderName, _, __) => placeholderName == "appname" ? appName : null;
});
```
